import type { Metadata } from "next";
import DashboardHead from "@/components/dashboard/Head";
import { DM_Sans, Poppins } from "next/font/google";
import "./../globals.css";
import Sidebar from "@/components/Sidebar";

const dm_sans = DM_Sans({ subsets: ["latin"] });
// const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="{dm_sans.className} flex min-h-screen items-stretch gap-5 p-5">
      <Sidebar />

      <main className="m-1 flex-1 sm:m-1">
        <DashboardHead />

        {children}
      </main>
    </div>
  );
}
