import type { Metadata } from "next";
import { DM_Sans, Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

const dm_sans = DM_Sans({ subsets: ["latin"] });
const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="{dm_sans.className} flex min-h-screen flex-row items-stretch gap-5 p-5">
        <Sidebar />

        {children}
      </body>
    </html>
  );
}
